# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestWork():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testWork(self):
    self.driver.get("http://sqwy.wt.com:5130/")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.CSS_SELECTOR, "span").click()
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "password").send_keys("123456")
    self.driver.find_element(By.NAME, "username").send_keys("18730001238")
    self.driver.find_element(By.NAME, "imgCode").click()
    self.driver.find_element(By.NAME, "imgCode").send_keys("2756")
    self.driver.find_element(By.ID, "login").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-submenu:nth-child(1) > .el-submenu__title > div").click()
    self.driver.find_element(By.LINK_TEXT, "事件处理").click()
    element = self.driver.find_element(By.LINK_TEXT, "事件处理")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "tab-1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-table__fixed-right span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-dialog__close").click()
    self.driver.find_element(By.LINK_TEXT, "我受理事件").click()
    element = self.driver.find_element(By.LINK_TEXT, "我受理事件")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".el-table__fixed-right .el-button:nth-child(1) > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-dialog__footer:nth-child(3) span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".app-main").click()
  
